name: hr_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  dartz: ^0.10.1
  get_storage: ^2.1.1
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  heroicons: ^0.11.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/images/
  
  fonts: 
    - family: Inter
      fonts:
        - asset: lib/shared/assets/font/Inter-VariableFont_opsz,wght.ttf
        - asset: lib/shared/assets/font/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic


